eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  datasource:
    url: jdbc:mysql:///zfz_basic?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#  boot:
#    admin:
#      client:
#        url: http://localhost:9001
logging:
  file: G:/zfz-logs/output.log